os:
  - osx

language: node_js

node_js:
  - '7'

branches:
  only:
    - master

script: ./script/cibuild

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
