#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew update

  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies..."
    brew bundle
  }
fi

if [ -f ".node-version" ] && [ -z "$(nodenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Node..."
  nodenv install --skip-existing
fi

if [ -f "package.json" ]; then
  echo "==> Installing Node dependencies..."
  npm install
fi
