#!/bin/sh

# script/doc: Generates any assets belonging to the documentation.

set -e

cd "$(dirname "$0")/.."

./node_modules/.bin/jsdoc \
  --configure .jsdoc.conf.json \
  --destination ./docs/ \
  --template ./node_modules/ink-docstrap/template \
  --readme README.md \
  --recurse \
  src
