#!/bin/sh

# script/lint: Runs a lint process on the code.

set -e

cd "$(dirname "$0")/.."

echo "==> Linting JavaScript files..."
./node_modules/eslint/bin/eslint.js src/**/*.js test/**/*.js

echo "==> Validating JSON data files..."
for f in data/*.json; do
  BASENAME=$(basename $f .json)
  ./node_modules/.bin/ajv validate -s data/$BASENAME.schema -d data/$BASENAME.json
done

echo "==> Validating licenses of dependencies..."
./node_modules/.bin/licensee --errors-only
