#!/bin/sh

# script/test: Tests the application.

set -e

cd "$(dirname "$0")/.."

script/build

./node_modules/.bin/babel --presets es2015 \
                          --out-dir lib/test/ \
                          test/

./node_modules/.bin/mocha --require babel-register --recursive --reporter dot
