#!/bin/sh

# script/test: Tests the application.

set -e

cd "$(dirname "$0")/.."

script/build

export ELECTRON_PATH=./node_modules/.bin/electron
export HERO_DATABASE_HOME=.

./node_modules/.bin/electron-mocha --renderer
