#!/bin/sh

# script/test: Tests the application.

set -e

cd "$(dirname "$0")/.."

script/build

./node_modules/.bin/babel --presets es2015 \
                          --out-dir lib/test/ \
                          test/

export ELECTRON_PATH=./node_modules/.bin/electron
export HERO_DATABASE_HOME=.

./node_modules/.bin/electron-mocha --require babel-register --recursive --reporter dot --renderer test/hero
./node_modules/.bin/electron-mocha --require babel-register --recursive --reporter dot --renderer test/renderer
